name: "TechTrends - Package with Docker"

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: starsoi/techtrends
          tags: |
            type=semver,pattern={{version}}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - 
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: ./project
          push: true
          tags: ${{ steps.meta.outputs.tags }}
